### PR TITLE
RE: Implement configuration of authorities #30 

### PR DESCRIPTION
**Pull request by faux-eccles**
1. Further improvements on reading the configuration from a JSON file.
2. Shared configuration object.
3. Some small documentation and spelling fixes.

### CODE REVIEW

**Comment by faux-eccles** [comment]
I think the authorities should be pulled out from the hosts module, I'll investigate dynamically loading them from a subdirectory eg:


> /
> | aker.py
> | hosts.py
> | authority.py
> | authorities / IPA.py
> | authorities / json.py

**Comment by anazmy** [comment]
Thanks man for the new pr ! 
Well it sounds a good idea to separate authorities for sake of code readability/maintenance , for the authorities subdir approach , what's your rationale here, some kind of modular plug-able setup ?

**Comment by faux-eccles** [comment]
I figured if it's resolved programmatically it can become easily extendable down the line.  It might also prevent the need to update the AuthorityFactory in case a new one is added as they won't be hardcoded in.
However at this point in time it doesn't seem that extra authorities are planned (Other than maybe AWS).
There may be a better approach, but I'm not sure of a way of registering each authority to the factory without explicitly loading them.

**Comment by anazmy** [comment]
Looks great ! , I will be picking up on having proper hosts object for caching now

**Pull request merged**
